### ISSUE TITLE
Drop instruction not implemented

### ISSUE THREAD

**Issue by vshymanskyy** [intel/wasm-micro-runtime#19]

**Comment by wenyongh** [comment]
Thanks vshymanskyy. DROP instruction is converted to DROP_32 or DROP_64 when loading wasm binary, according to the data type in stack, so it is not implemented in interpreter.

**Comment by vshymanskyy** [comment]
@wenyongh thanks, did not notice it at first.
This leads to another question! Is there a way to pre-process the original wasm file beforehand?

**Comment by wenyongh** [comment]
@vshymanskyy, yes, we perform the type safe checking when loading wasm binary, based on a type interpreter, which is to execute the bytecode where operands are types instead of real data values. For example, for i32.add opcode, the type interpreter checks and pops two i32 types from stack, and pushes one i32 type back to stack. And when processing DROP instruction, it checks operand type in stack top, if it is I32 or F32, we connvert DROP to DROP_32, and if it is I64 or F64, we convert DROP to DROP_64.
