### ISSUE TITLE
Can't sppourt all standard library?

### ISSUE THREAD

**Issue by darkmoon233** [intel/wasm-micro-runtime#86]
I can run the example given.But when i try my file, iwasm occurs some errors!
My code:
```cpp
#include <stdio.h>
#include <string.h>
#include <ctime>
int fibR(int n)
{
    if (n < 2) return n;
    return (fibR(n-2) + fibR(n-1));
}
int main()
{
    clock_t t = clock();
    char str[50];
    int len;
    strcpy(str, "This is runoob.com");
    len = strlen(str);
    t = clock() - t;
    printf ("%f\n",((float)t)/CLOCKS_PER_SEC);
    return 0;
}
```
error
```
Load import section failed: resolve import function (env, _clock) failed.
```
What confused me is that the functions of `<stdio.h>` and `<string.h>` can be called correctly, but the functions of `<ctime.h>` are not.

I have noticed that `/core/iwasm/products/linux/main.c` contains code like that:
```c
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <stdlib.h>
#include <string.h>
#include "bh_platform.h"
#include "wasm_assert.h"
#include "wasm_log.h"
#include "wasm_platform_log.h"
#include "wasm_thread.h"
#include "wasm_export.h"
#include "wasm_memory.h"
#include "bh_memory.h"
```
The `main.c` only contains `<stdlib.h>` and `<string.h>` ,so i add `#include <time.h>`.I reran the `make` and `cmake` command .But iwasm still occurs the same error!

Is there a way to allow iwasm to support other standard library files?

**Comment by wenyongh** [comment]
Currently wamr supports a subset of libc API's, including printf/memcpy/strcpy/malloc/free and so on, please refer to "Built-in application library" in README. And developer may extend the libc API's, you can add the clock wrapper function in file: core/iwasm/lib/native/libc/libc_wrapper.c, registering the wrapper API to array native_func_defs, please refer to the implementation of other wrapper functions, such as strcpy, memcpy, strlen. Or you can also add the wrapper function to file ext_lib_export.c.

In the future, we may enable WASI to support libc, and in that mode, developer needn't implement the wrapper function of libc API. But the size of the wasm binary file will increase, since part of the libc source code is compiled into the wasm file.
