### ISSUE TITLE
 Is it possible to import an external class?

### ISSUE THREAD

**Issue by darkmoon233** [intel/wasm-micro-runtime#95]
I can import external functions through the wasm-micro-runtime, but what about classes?

I found that  the WASM knows nothing about the class when I want to use an external class in WASM. I can only use imported functions to simulate the use of external classes, which is too difficult for some complex classes (such as STL classes).

for example ,I simulated some of the operations of std::string.

```cpp
// wasm-src code
extern "C"
{
	void init_string(void* str_ptr);
	size_t get_string_size(void* str_ptr);
	void call_string_pop_back(void* ptr);
    bool wasm_call_string(void* _str_add, char* _fun_name,int argv,unsigned int argc[]);

}
class string{
public:
	string(){
		str_ptr = malloc(STRING_SIZE);
		init_string(str_ptr);
	}
	size_t size() {
		char char_ptr[] = "size";
		wasm_call_string(str_ptr,char_ptr);
		return get_string_size(str_ptr);
	}
	void pop_back(){
		printf("call pop_back()\n");
		call_string_pop_back(str_ptr);
	}
private:
	void* str_ptr;
};
```
```cpp
// cpp code
void init_string(void* ptr){
        wasm_module_inst_t module_inst = wasm_runtime_get_current_module_inst();
        void* str_ptr = wasm_runtime_addr_app_to_native(module_inst,(int)ptr);
        new (str_ptr) std::string;
        *(std::string*)str_ptr += "hello world";
        std::cout << *(std::string*)str_ptr << std::endl;
    }
    size_t get_string_size(void* ptr) {
        return _str_ptr->size();
    }
    void call_string_pop_back(void* ptr){
        _str_ptr->pop_back();
    }
```
But std::string is really a complex class, it has more than 40 functions(Not counting overload functions).There must be a conversion for each function. So it is too difficult to use std::string in wasm.Of course other external classes are like this.

Is there a convenient way to use external classes?

**Comment by wenyongh** [comment]
Hi @darkmoon233, for the security and toolchain reason, it is really not easy to directly access the external class/structure created outside wasm app. The structure layouts of wasm app and native may be different, since their toolchain and target platform are different; and also there is address conversion issue.

If you feel not convenient to wrap each std::string member function, could you try another method: only write one wrapper function for the std::string class, and using command ID and argument array to call the std::string member functions:
      void std_string_native_call(int cmd, unsigned *argv, int argc);
For example, in native lib:

    enum {
      STD_STRING_CREATE,
      STD_STRING_GET_SIZE,
      STD_STRING_PUSH_BACK,
      STD_STRING_POP_BACK
    };
    static void std_string_native_call(int cmd, int argv_offset, int argc)
    {
      wasm_module_inst_t module_inst;
      unsigned *argv;
      std::string *str = NULL;
      module_inst = get_module_inst();
      argv = (unsigned*)wasm_runtime_addr_app_to_native(module_inst, argv_offset);

      switch (cmd) {
        case STD_STRING_CREATE:
            str = new std::string;
            memcpy(argv, &str, sizeof(unsigned*));
            break;
        case STD_STRING_GET_SIZE:
            memcpy(&str, argv, sizeof(unsigned*));
            argv[0] = str->size();
            break;
        case STD_STRING_PUSH_BACK:
            memcpy(&str, argv, sizeof(unsigned*));
            str->push_back((char)argv[2]);
            break;
    }

Then in wasm app, you can pass command to the native function to create string, push back, get size:
 
    unsigned func_argv[8];
    std_string_native_call(STD_STRING_CREATE, func_argv, 0);
    memcpy(&func_argv, &str, 2);
    func_argv[2] = 'a';
    std_string_native_call(STD_STRING_PUSH_BACK, func_argv, 3);

    memcpy(&func_argv, &str, 2);
    std_string_native_call(STD_STRING_GET_SIZE, func_argv, 2);
    size = func_argv[0];
    printf("size: %d\n", size);

Here is the source code of the test case, hope it is helpful for you.
[test_std_string.zip](https://github.com/intel/wasm-micro-runtime/files/3491602/test_std_string.zip)
